[package]
name = "willkamp-com"
version = "0.1.0"
authors = ["William Kamp <manimaul@gmail.com>"]
edition = "2018"
publish = false

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
yew = "0.17.3"
yew-router = "0.14.0"
strum = "0.19"
strum_macros = "0.19"
wasm-bindgen = "0.2.67"
